name: Package CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Installation Environment
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package --file pom.xml ;mvn deploy

#    - name: package
#      run: mvn -B package --file pom.xml
#    - name: deploy
#      run: mvn -X deploy -Dregistry=https://maven.pkg.github.com/supergaga -Dtoken=${{ secrets.deploy }}